# Generated by Django 4.1.5 on 2023-01-13 02:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("monobank", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_under_moderation", models.BooleanField(default=True)),
                ("name", models.CharField(default="", max_length=100)),
                ("description", models.CharField(default="", max_length=512)),
                ("ending_date", models.DateTimeField(null=True)),
                ("is_finished", models.BooleanField(default=False)),
                ("report_text", models.CharField(default="", max_length=512)),
                (
                    "report_images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.ImageField(upload_to="static"), default=list, size=None
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "monobank_jar",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="monobank.monobankjar"
                    ),
                ),
            ],
            options={
                "permissions": (("view_post", "Can view post"),),
                "get_latest_by": "created_at",
                "default_permissions": ("add", "change", "delete"),
            },
        ),
    ]
