# Generated by Django 3.2.10 on 2023-01-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="is_finished",
        ),
        migrations.AddField(
            model_name="lot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
