# Generated by Django 4.1.5 on 2023-01-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
