# Generated by Django 4.1.5 on 2023-01-13 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0002_lot_is_finished"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lot",
            options={"default_permissions": ("add", "change", "delete")},
        ),
    ]
