# Generated by Django 4.1.5 on 2023-01-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0003_alter_lot_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lot",
            options={
                "default_permissions": ("add", "change", "delete"),
                "get_latest_by": "created_at",
                "permissions": (("view_post", "Can view post"),),
            },
        ),
    ]
