# Generated by Django 3.2.10 on 2023-03-17 10:44

from django.db import migrations, models

import lots.constants


class Migration(migrations.Migration):

    replaces = [
        ("lots", "0005_auto_20230317_0941"),
        ("lots", "0006_alter_lot_status"),
        ("lots", "0007_remove_lot_status"),
        ("lots", "0008_lot_status"),
    ]

    dependencies = [
        ("lots", "0004_lot_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lot",
            options={
                "default_permissions": ("add", "change", "delete"),
                "get_latest_by": "created_at",
                "ordering": ("created_at",),
                "permissions": (("view_post", "Can view post"),),
            },
        ),
        migrations.RemoveField(
            model_name="lot",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="is_under_moderation",
        ),
        migrations.AddField(
            model_name="lot",
            name="status",
            field=models.CharField(
                choices=[("MODERATION", "Under moderation"), ("ACTIVE", "Active"), ("CLOSED", "Closed")],
                default=lots.constants.LOT_STATUS["MODERATION"],
                max_length=50,
            ),
        ),
    ]
