# Generated by Django 3.2.10 on 2023-03-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0006_auto_20230317_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="description",
            field=models.CharField(default="", max_length=2048),
        ),
    ]
