# Generated by Django 3.2.10 on 2023-03-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lots", "0007_alter_lot_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
