# Generated by Django 4.1.5 on 2023-01-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False, help_text="Designates that user has all perms", verbose_name="superuser status"
            ),
        ),
    ]
