# Generated by Django 4.1.5 on 2023-01-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donate_ukraine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default=None, max_length=50)),
                ("file", models.ImageField(default=None, upload_to="media/images/lots")),
                ("lot_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="donate_ukraine.lot")),
            ],
        ),
    ]
