# Generated by Django 3.2.10 on 2023-01-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotimage",
            name="file",
            field=models.ImageField(default=None, upload_to="images/lots"),
        ),
    ]
