# Generated by Django 4.1.4 on 2022-12-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_remove_lotimage_img_lotimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lotimage",
            old_name="image",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="lotimage",
            old_name="lot",
            new_name="lot_id",
        ),
    ]
