# Generated by Django 3.2.10 on 2023-01-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_alter_lotimage_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lotimage",
            name="name",
        ),
        migrations.AlterField(
            model_name="lotimage",
            name="file",
            field=models.ImageField(upload_to="images/lots"),
        ),
    ]
