# Generated by Django 4.1.4 on 2022-12-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_rename_image_lotimage_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotimage",
            name="file",
            field=models.ImageField(default=None, upload_to="images/lots"),
        ),
    ]
