# Generated by Django 4.1.4 on 2022-12-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonobankJar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jar_id", models.CharField(max_length=40)),
                ("current_balance", models.IntegerField()),
                ("highest_bid", models.IntegerField()),
                ("last_updated", models.DateTimeField()),
            ],
        ),
    ]
