# Generated by Django 4.1.4 on 2022-12-25 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monobankjar",
            name="jar_id",
        ),
        migrations.AddField(
            model_name="monobankjar",
            name="link",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="monobankjar",
            name="monobank_id",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="monobankjar",
            name="current_balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monobankjar",
            name="highest_bid",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monobankjar",
            name="last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 25, 2, 0, 8, 181858, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
