# Generated by Django 3.2.10 on 2023-01-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monobank", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monobankjar",
            name="link",
        ),
        migrations.AddField(
            model_name="monobankjar",
            name="send_id",
            field=models.TextField(default="", max_length=40),
        ),
    ]
