# Generated by Django 4.1.4 on 2022-12-25 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0002_remove_monobankjar_jar_id_monobankjar_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monobankjar",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
