# Generated by Django 4.1.4 on 2022-12-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0003_alter_monobankjar_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="monobankjar",
            name="title",
            field=models.CharField(default="", max_length=40),
        ),
    ]
