# Generated by Django 4.1.4 on 2023-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0004_monobankjar_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monobankjar",
            name="link",
            field=models.URLField(default="", max_length=40),
        ),
    ]
