# Generated by Django 4.1.4 on 2023-01-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0005_alter_monobankjar_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="monobankjar",
            name="goal",
            field=models.IntegerField(default=0),
        ),
    ]
