version: '3'
services:
  db:
    image: 'postgres:latest'
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  donate_ukraine:
    restart: always
    ports:
      - "8000:8000"
    build: .
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/code
    environment:
      - MAIL_API_KEY=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
      - DJANGO_SETTINGS_MODULE=settings.compose
      - AWS_ACCESS_KEY_ID=AKIA3YGD4DJ7WJK3XM7X
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=donate-ua-bucket
