[tool.black]
line-length = 120
target_version = ['py38']
force-exclude = 'urls.py'

[tool.isort]
profile="black"
overwrite_in_place = true
indent = 4
combine_star = true
combine_as_imports = true
line_length = 120
lines_after_imports = 2

[tool.flake8]
exclude = '.git,__pycache__,postgres-data,migrations,static'
max-line-length = 120
