# Generated by Django 4.1.3 on 2022-11-19 06:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donate_ukraine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="report_images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(upload_to=""), default=list, size=None
            ),
        ),
    ]
