# Generated by Django 4.1.3 on 2022-11-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_ukraine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lot',
            name='report_images',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lot',
            name='report_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='lot',
            name='requisites',
            field=models.CharField(default='', max_length=512),
        ),
    ]
