# Generated by Django 4.1.4 on 2022-12-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donate_ukraine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="photos",
        ),
    ]
