# Generated by Django 4.1.4 on 2022-12-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donate_ukraine", "0002_remove_lot_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
