# Generated by Django 4.1.3 on 2022-11-19 08:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_ukraine', '0002_alter_lot_report_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='requisites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=512), default=list, size=None),
        ),
    ]
