# Generated by Django 4.1.4 on 2022-12-16 13:47

from django.db import migrations
import donate_ukraine.models


class Migration(migrations.Migration):

    dependencies = [
        ("donate_ukraine", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", donate_ukraine.models.UserManager()),
            ],
        ),
    ]
