# Generated by Django 4.1.4 on 2022-12-24 21:11

from django.db import migrations, models
import django.db.models.deletion
import donate_ukraine.models


class Migration(migrations.Migration):

    dependencies = [
        ("monobank", "0001_initial"),
        ("donate_ukraine", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", donate_ukraine.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="lot",
            name="monobank_jar",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="monobank.monobankjar"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="api_token",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
