# Generated by Django 4.1.4 on 2023-01-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donate_ukraine", "0004_alter_user_managers_lot_monobank_jar_user_api_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="api_token",
            field=models.CharField(max_length=60),
        ),
    ]
