# Generated by Django 4.1.4 on 2023-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donate_ukraine", "0006_remove_lot_requisites_lot_is_under_moderation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="ending_date",
            field=models.DateTimeField(null=True),
        ),
    ]
